[
    {
        "type": "message",
        "user": "U12452RAP",
        "text": "<@U0UHG4VP1> or others who can help stop a wrong build <https:\/\/jenkins.hyperledger.org\/job\/fabric-verify-sdk-py-x86_64\/55\/>",
        "ts": "1482999783.001217"
    },
    {
        "type": "message",
        "user": "U0UHG4VP1",
        "text": "done. I think it would have timed out anyway",
        "ts": "1482999898.001218",
        "reactions": [
            {
                "name": "+1",
                "users": [
                    "U12452RAP"
                ],
                "count": 1
            }
        ]
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "<@U0KM61BCP> <@U0UHG4VP1> <@U0KPFAZNF> the merging of <https:\/\/gerrit.hyperledger.org\/r\/#\/c\/3319> early this morning broke the z build.  hopefully, we can get the merge job ssh credential issue resolved and then we can start to look at what we need to do to allow voting for z (for both verify and merge).",
        "edited": {
            "user": "U0YK3KKCY",
            "ts": "1483024824.000000"
        },
        "ts": "1483024714.001219"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "i've opened up an issue <https:\/\/jira.hyperledger.org\/browse\/FAB-1487> and have chatted with the author of CR 3319 to resolve this issue.",
        "ts": "1483024800.001222"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "it looks like this merged change might affect all platforms.  not 100% sure, but it looks like core\/util\/utils.go:28:  \"<http:\/\/github.com\/hyperledger\/fabric\/metadata|github.com\/hyperledger\/fabric\/metadata>\" was never changed to reflect its new name\/location.",
        "ts": "1483026635.001225"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "```\n\ncore\/util\/utils.go:28:2: cannot find package \"<http:\/\/github.com\/hyperledger\/fabric\/metadata|github.com\/hyperledger\/fabric\/metadata>\" in any of:\n\t\/opt\/gopath\/src\/github.com\/hyperledger\/fabric\/vendor\/github.com\/hyperledger\/fabric\/metadata (vendor tree)\n\t\/opt\/go\/src\/github.com\/hyperledger\/fabric\/metadata (from $GOROOT)\n\t\/opt\/gopath\/src\/github.com\/hyperledger\/fabric\/metadata (from $GOPATH)\nMakefile:133: recipe for target 'build\/docker\/bin\/peer' failed\n```",
        "ts": "1483026666.001226"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "This?",
        "ts": "1483026669.001227"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "See above",
        "ts": "1483026747.001228"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "i tried to warn folks",
        "ts": "1483026760.001229"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "I don't understand, how did it pass CI?",
        "ts": "1483026789.001230"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "not sure how the merge job got this through",
        "ts": "1483026790.001231"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "exactly",
        "ts": "1483026797.001232"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "needs to be looked at",
        "ts": "1483026805.001233"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "not even the merge job, the verify",
        "ts": "1483026808.001234"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "weird",
        "ts": "1483026810.001235"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "the verify last ran on 12\/18 if you look at the cr",
        "ts": "1483026826.001236"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "it was never run again",
        "ts": "1483026832.001237"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "so it needed to be rebased then?",
        "ts": "1483026840.001238"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "i'm not sure what the exact procedure should be",
        "ts": "1483026857.001239"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "I guess the orange circle was ignored",
        "ts": "1483026861.001240"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "not an expert in this area",
        "ts": "1483026862.001241"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "something \"fell through the cracks\"",
        "ts": "1483026928.001242"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "when i download patch set #2 for CR 3319, the reference to fabric\/metadata in utils.go has been removed.  i'm not sure why the reference is still in the current codebase.",
        "edited": {
            "user": "U0YK3KKCY",
            "ts": "1483027714.000000"
        },
        "ts": "1483027363.001243"
    },
    {
        "type": "message",
        "user": "U0YK3KKCY",
        "text": "<@U0ZJZBJLF>, i suspect that you're right... a rebase was never done as the fabric\/metadata line in utils.go was added 19 days ago.",
        "edited": {
            "user": "U0YK3KKCY",
            "ts": "1483027568.000000"
        },
        "ts": "1483027538.001244"
    }
]