[
    {
        "type": "message",
        "user": "U10MXEXL3",
        "text": "<@U0VKPD6A2> - Yes I am following the steps on the tutorial page",
        "ts": "1467903211.000168"
    },
    {
        "type": "message",
        "user": "U0VKPD6A2",
        "text": "<@U10MXEXL3>: great.  do you see the txnvalidator file in \/project\/sawtooth-validator\/bin ?",
        "ts": "1467903423.000169"
    },
    {
        "type": "message",
        "user": "U10MXEXL3",
        "text": "<@U0VKPD6A2>: yes there is a txnvalidator file in \/project\/sawtooth-validator\/bin",
        "ts": "1467903855.000170"
    },
    {
        "type": "message",
        "user": "U1H7F590E",
        "text": "This should be ran from the sawtooth-validator .\/bin\/txnvalidator -v --http 8800 --config \/project\/sawtooth-docs\/source\/tutorial\/txnvalidator.js",
        "edited": {
            "user": "U1H7F590E",
            "ts": "1467909780.000000"
        },
        "ts": "1467909693.000171"
    },
    {
        "type": "message",
        "user": "U1H7F590E",
        "text": "<@U10MXEXL3>: were you in the correct directory?",
        "ts": "1467909826.000173"
    },
    {
        "type": "message",
        "user": "U10MXEXL3",
        "text": "Yes I am I think it is an environment issue a simple echo directly after '#!\/usr\/bin\/env python' does not result in any output, just the original error",
        "ts": "1467911187.000174"
    },
    {
        "type": "message",
        "user": "U10MXEXL3",
        "text": "Fixed it. The file had a CR-LF after the '#!\/usr\/bin\/env python' line. Thanks to <http:\/\/askubuntu.com\/questions\/372672\/what-could-cause-a-script-to-fail-to-find-python-when-it-has-usr-bin-env-pyt>",
        "attachments": [
            {
                "title": "what could cause a script to fail to find python when it has `#!\/usr\/bin\/env python` in the first line?",
                "title_link": "http:\/\/askubuntu.com\/questions\/372672\/what-could-cause-a-script-to-fail-to-find-python-when-it-has-usr-bin-env-pyt",
                "text": "Trying to get casperjs running on Ubuntu 12.04. After installing it when I run I get: 09:20 $ ll \/usr\/local\/bin\/casperjslrwxrwxrwx 1 root root 26 Nov 6 16:49 \/usr\/local\/bin\/casperjs -&gt; \/opt\/",
                "fallback": "what could cause a script to fail to find python when it has `#!\/usr\/bin\/env python` in the first line?",
                "thumb_url": "http:\/\/cdn.sstatic.net\/Sites\/askubuntu\/img\/apple-touch-icon@2.png?v=c492c9229955&a",
                "from_url": "http:\/\/askubuntu.com\/questions\/372672\/what-could-cause-a-script-to-fail-to-find-python-when-it-has-usr-bin-env-pyt",
                "thumb_width": 316,
                "thumb_height": 316,
                "service_icon": "http:\/\/cdn.sstatic.net\/Sites\/askubuntu\/img\/favicon.ico?v=eff8fd315b9e",
                "service_name": "askubuntu.com",
                "id": 1
            }
        ],
        "ts": "1467913038.000175",
        "reactions": [
            {
                "name": "woo",
                "users": [
                    "U0UHG4VP1"
                ],
                "count": 1
            },
            {
                "name": "+1",
                "users": [
                    "U0VKPD6A2"
                ],
                "count": 1
            }
        ]
    },
    {
        "type": "message",
        "user": "U10MXEXL3",
        "text": "Now I get the error: ImportError: No module named sawtooth.config",
        "ts": "1467919057.000177"
    },
    {
        "type": "message",
        "user": "U10MXEXL3",
        "text": "I see it under sawtooth-core",
        "ts": "1467919125.000178"
    },
    {
        "type": "message",
        "user": "U1L6PRGTF",
        "text": "<@U10MXEXL3>: what does \u2018echo $PYTHONPATH\u2019 get you?",
        "ts": "1467920319.000179"
    },
    {
        "type": "message",
        "user": "U10MXEXL3",
        "text": ".:\/projects\/sawtooth-core",
        "ts": "1467920365.000180"
    },
    {
        "type": "message",
        "user": "U10MXEXL3",
        "text": "I think my env is hosed. I needed to perform many more pythin related installs than indicated in the tutorial.",
        "ts": "1467920529.000181"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "interesting, so when you checked it out from git, it must be converting the files to CRLF?",
        "ts": "1467920532.000182"
    },
    {
        "type": "message",
        "user": "U10MXEXL3",
        "text": "good point",
        "ts": "1467920549.000183"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "if so, the solution would be to re-clone the repos with (perhaps) --config core.autocrlf=input",
        "ts": "1467920852.000184"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "I'm not usually a windows user, so haven't tried that",
        "ts": "1467920874.000185"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "if it fixes the issue though, we could update our tutorial with (at least) a note",
        "ts": "1467920909.000186"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "my read of the git docs though, suggests that setting would still convert it to CRLF on checkout, but <@U0Y4ZF0QM> claims that's his setting on Windows",
        "ts": "1467921072.000187"
    },
    {
        "type": "message",
        "user": "U10MXEXL3",
        "text": "thx",
        "ts": "1467926632.000188"
    },
    {
        "user": "U1ADSTE0N",
        "text": "<@U1ADSTE0N|viewer> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1467945988.000189"
    }
]