[
    {
        "user": "U0ZKTJABC",
        "text": "<@U0ZKTJABC|praveen.j> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1481140561.000052"
    },
    {
        "type": "message",
        "user": "U0ZKTJABC",
        "text": "<@U0YNFB22X> Isn't one chaincode calling another chaincode a synchronous call and part of the same transaction context? If the second chaincode execution resulted in an error, shouldn't it be propagated as an error at the transaction level? This is the error <@U2LHDBZM0> is facing.",
        "attachments": [
            {
                "fallback": "[December 2nd, 2016 2:05 PM] satheesh: The transaction execution in cc2 happens async after it's submitted",
                "ts": "1480667748.000276",
                "author_subname": "satheesh",
                "channel_id": "C1D3VRND8",
                "channel_name": "java-chaincode",
                "is_msg_unfurl": true,
                "text": "The transaction execution in cc2 happens async after it's submitted",
                "author_name": "Satheesh Kathamuthu",
                "author_link": "https:\/\/hyperledgerproject.slack.com\/team\/satheesh",
                "author_icon": "https:\/\/secure.gravatar.com\/avatar\/3cfaa84113b861c6ab1e2d4214b22201.jpg?s=48&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0016-48.png",
                "mrkdwn_in": [
                    "text"
                ],
                "color": "D0D0D0",
                "from_url": "https:\/\/hyperledgerproject.slack.com\/archives\/java-chaincode\/p1480667748000276",
                "is_share": true,
                "footer": "Posted in #java-chaincode"
            }
        ],
        "ts": "1481140666.000053"
    },
    {
        "user": "U1HN4CVT9",
        "text": "<@U1HN4CVT9|darrenst> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1481155905.000054"
    }
]