[
    {
        "type": "message",
        "user": "U1KFCPFQA",
        "text": "<@U0ULK2JPP> <@U0UKTPMG8> I pulled the latest from master this morning, and now my committer service in peer won\u2019t start, any ideas?",
        "edited": {
            "user": "U1KFCPFQA",
            "ts": "1478610145.000000"
        },
        "ts": "1478609933.000676"
    },
    {
        "type": "message",
        "user": "U1KFCPFQA",
        "text": "12:58:49.002 [peer] ensureConnected -&gt; DEBU 0bb Starting Peer reconnect service (touch service), with period = 6s\n12:58:49.002 [noopssinglechain] NewCommitter -&gt; INFO 0bc Creating committer for single noops endorser\n12:58:49.002 [nodeCmd] serve -&gt; INFO 0bd Starting peer with ID=name:\"jdoe\" , network ID=dev, address=0.0.0.0:7051, rootnodes=, validator=true\nCould not start solo committer(EOF), continuing without committer",
        "edited": {
            "user": "U1KFCPFQA",
            "ts": "1478610040.000000"
        },
        "ts": "1478610022.000677"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "<@U1KFCPFQA> did you add CORE_PEER_COMMITTER_LEDGER_ORDERER=0.0.0.0:5151 to the peer command ?",
        "ts": "1478611348.000680"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "(will try too with latest)",
        "ts": "1478611435.000681"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "<@U1KFCPFQA> I\u2019m getting an error too",
        "ts": "1478614073.000682"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "will check and update",
        "ts": "1478614083.000683"
    },
    {
        "user": "U2PB5LKLG",
        "text": "<@U2PB5LKLG|drasko> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1478615525.000684"
    },
    {
        "type": "message",
        "user": "U1KFCPFQA",
        "text": "<@U0ULK2JPP> I re-pulled the latest from master and rebuilt order and peer.  Now it comes up, but transactions fail with error:",
        "ts": "1478619565.000685"
    },
    {
        "type": "message",
        "user": "U1KFCPFQA",
        "text": "Error getting tx(proto: bad wiretype for field protos.Transaction2.Version: got wiretype 2, want 0)...dropping block",
        "ts": "1478619568.000686"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "<@U1KFCPFQA>  correct",
        "edited": {
            "user": "U0ULK2JPP",
            "ts": "1478619818.000000"
        },
        "ts": "1478619786.000687"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "I see that too",
        "ts": "1478619791.000688"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "will try to get a fix soon",
        "ts": "1478619804.000689"
    },
    {
        "type": "message",
        "user": "U1KFCPFQA",
        "text": "<@U0ULK2JPP> I opened Jira defect: <https:\/\/jira.hyperledger.org\/browse\/FAB-1040>",
        "ts": "1478633115.000691"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "thanks <@U1KFCPFQA>",
        "ts": "1478633174.000692"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "<@U1KFCPFQA> fixed in <https:\/\/gerrit.hyperledger.org\/r\/#\/c\/2349\/>",
        "ts": "1478642371.000693"
    }
]