[
    {
        "type": "message",
        "user": "U1AU8DRQR",
        "text": "<https:\/\/github.com\/hyperledger\/fabric\/pull\/1754> I have a strange error here:  Error opening DB IO error: lock \/var\/hyperledger\/test\/ledger_test\/db\/LOCK: Resource temporarily unavailable\nIsn't this a Jenkins\/environment problem? Can somebody take a look?",
        "attachments": [
            {
                "service_name": "GitHub",
                "title": "Add transaction rejection events by gabre \u00b7 Pull Request #1754 \u00b7 hyperledger\/fabric \u00b7 GitHub",
                "title_link": "https:\/\/github.com\/hyperledger\/fabric\/pull\/1754",
                "text": "This change adds a new type of events: transaction rejection. These events are sent out to listeners in case the corresponding chain code of a transaction exited with error. Description See the s...",
                "fallback": "GitHub: Add transaction rejection events by gabre \u00b7 Pull Request #1754 \u00b7 hyperledger\/fabric",
                "thumb_url": "https:\/\/avatars2.githubusercontent.com\/u\/5565153?v=3&s=400",
                "from_url": "https:\/\/github.com\/hyperledger\/fabric\/pull\/1754",
                "thumb_width": 420,
                "thumb_height": 420,
                "service_icon": "https:\/\/a.slack-edge.com\/e8ef6\/img\/unfurl_icons\/github.png",
                "id": 1
            }
        ],
        "ts": "1466411702.000036"
    },
    {
        "type": "message",
        "user": "U11HH3P7Y",
        "text": "Hi <@U1AU8DRQR> : Please refer issue #1907 and this was fixed and merged with PR#1877",
        "ts": "1466429044.000038"
    }
]