[
    {
        "type": "message",
        "user": "U2SE05657",
        "text": "Hello! I'm running through java code with those commands \n`docker run --rm -i -v \/var\/run\/docker.sock:\/var\/run\/docker.sock -p 7054:7054 hyperledger\/fabric-membersrvc membersrvc` \n`docker run --rm -i -v \/var\/run\/docker.sock:\/var\/run\/docker.sock -e CORE_LOGGING_LEVEL=DEBUG -e CORE_PEER_ID=vp0 -e CORE_PEER_ADDRESSAUTODETECT=true hyperledger\/fabric-peer peer node start` \n`docker run --rm -i -v \/var\/run\/docker.sock:\/var\/run\/docker.sock -e CORE_PEER_ID=test_vp%d -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.3:7051 hyperledger\/fabric-peer peer node start`. I created instance of class where I run one peer, and sending and getting messages. The question is: why when I'm getting messages from root peer I got every message I invoke through all peers, but when I'm getting messages from not root peer, I am getting only those messages, that I invoke to this peer. Info on blockchain should be kept on all peers isn't it?",
        "edited": {
            "user": "U2SE05657",
            "ts": "1479747934.000000"
        },
        "ts": "1479747905.000452"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "<@U2SE05657>  which method are you invoking? The invoke\/deploy transactions are supposed to be broadcasted to all nodes, while query will be only executed on the node you select.",
        "ts": "1479781214.000455"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "Hi i am using fabric-java-sdk and getting error \"The import org.hyperledger.protos cannot be resolved\"",
        "ts": "1479790160.000456"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "<@U1F1CU61Y> how are you building the sdk? try ```mvn install``` this will create the java files from proto files",
        "ts": "1479790494.000457"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "@matlaf I have run mvn goals clean and build",
        "ts": "1479790519.000458"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "and i got message build successful but still its showing the same error in eclipse",
        "ts": "1479790551.000459"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U1Y2R5C9L> can you please help me to resolve the problem ?",
        "ts": "1479790723.000460"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "Sorry it is successful when i skip tests",
        "ts": "1479790818.000461"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "because in test it gives error \"Identity or token does not match\"",
        "ts": "1479790839.000462"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "\"Identity or token does not match\" is a different error because you are already enrolled on CA",
        "ts": "1479791693.000463"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "how you are including the SDK in your project in eclipse?",
        "ts": "1479791713.000464"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "are you using maven dependency or adding SDK project as a project dependency?",
        "ts": "1479791735.000465"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "I have just imported java sdk project as existing maven project",
        "ts": "1479792207.000466"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "Right click on the pom file of sdk project, and select run as -&gt; maven generate-sources",
        "ts": "1479793531.000467"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U1Y2R5C9L>  i am getting following error:-\n\nTests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec &lt;&lt;&lt; FAILURE!\ntestGenerateDirectoryHash(org.hyperledger.fabric.sdk.SDKUtilTest)  Time elapsed: 0 sec  &lt;&lt;&lt; ERROR!\njava.io.IOException: The chaincode path \"C:\\Go\\bin\\src\\<http:\/\/github.com|github.com>\\hyperledger\\fabric\\examples\\chaincode\\java\\Example\" is invalid\n\tat org.hyperledger.fabric.sdk.helper.SDKUtil.generateDirectoryHash(SDKUtil.java:92)\n\tat org.hyperledger.fabric.sdk.SDKUtilTest.testGenerateDirectoryHash(SDKUtilTest.java:43)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)\n\tat org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)\n\tat org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)",
        "ts": "1479793783.000468"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "btw i have run   generate-source but its still showing same marker.",
        "ts": "1479793888.000469"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "and my chaincode java file location is C:\\Go\\bin\\src\\<http:\/\/github.com|github.com>\\hyperledger\\fabric\\examples\\cahincode\\java\\Example\\src\\main\\example\\Example.java",
        "ts": "1479793935.000470"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "From the test case failure, it seems that java is unable to read the directory C:\\Go\\bin\\src\\<http:\/\/github.com|github.com>\\hyperledger\\fabric\\examples\\chaincode\\java\\Example",
        "ts": "1479795147.000471"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U1Y2R5C9L>  one more thing i want to confirm test.properties file need to be create manually ?",
        "ts": "1479795412.000472"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "No, this will be automatically created once the enrollment\/registration is successful",
        "ts": "1479795733.000473"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "Okay",
        "ts": "1479795844.000474"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U1Y2R5C9L> i have removed \/var\/hyperledger\/production directory from both docker images and committed",
        "ts": "1479795881.000475"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "i am able to login using CLI",
        "ts": "1479795888.000476"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "but in java sdk still i am facing following error \n\nCaused by: io.grpc.StatusRuntimeException: UNKNOWN: Identity or token does not match.\n\tat io.grpc.Status.asRuntimeException(Status.java:536)\n\tat io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)\n\tat io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)\n\tat org.hyperledger.protos.ECAPGrpc$ECAPBlockingStub.createCertificatePair(ECAPGrpc.java:321)\n\tat org.hyperledger.fabric.sdk.MemberServicesImpl.enroll(MemberServicesImpl.java:190)\n\t... 24 more",
        "ts": "1479795905.000477"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "if you logged in from CLI, please remove the \/var\/hyperledger\/production again and also delete the test.properties from client :slightly_smiling_face:",
        "ts": "1479795945.000478"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "yeah i have done that already",
        "ts": "1479795961.000479"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "If you logged in once, you won't be able to login again",
        "ts": "1479795975.000480"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "also i have captured tcpdump everything is going good but i dont know why i am facing error.",
        "ts": "1479795994.000481"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "after deleting the directory, please don't login from cli",
        "ts": "1479796015.000482"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "yes i have not logged in again using CLI",
        "ts": "1479796046.000483"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "If test.properties in also deleted on client side, then the only possible answer is that either the user does not exist or the password is wrong",
        "ts": "1479796191.000484"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "Oh but everything is okay i am also not able to understand the problem :disappointed:",
        "ts": "1479796233.000485"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "one more thing it also shows below warning:-\n\nNov 22, 2016 12:00:18 PM org.hyperledger.fabric.sdk.FileKeyValStore loadProperties\nWARNING: Could not find the file \"C:\\Users\\ankit\/test.properties\"",
        "ts": "1479796267.000486"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "That's fine, this is to let user know that if they were expecting an existing key value store, it does not exist, so will be created when we feel the need to save something",
        "ts": "1479796350.000487"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "Okay",
        "ts": "1479796391.000488"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "So, any other idea what should be the next course of action ?",
        "ts": "1479796472.000489"
    }
]